"""
Dummy data feeder to create JIRA tickets
This simulates DB data for now.
"""
from database.database_operations import insert_jira_ticket_details
from src.plugins.jira_ticketing.notifier import send_teams_notification
from connections.jira_connections import JiraClient


def build_description(data: dict, rca: str) -> str:
    """Format Jira ticket description"""
    return f"""
            *Issue Details:*\n
            Tool: {data['error_tool']} 
            Stack Trace: {data['stack_trace']} \n\n

            {rca}

            *Environment:* Production

            Auto-generated by monitoring system.
            """

def jira_ticket(incident, rca, db_manager):
    try:
        from config.settings import JIRA_URL, JIRA_USERNAME, JIRA_API_TOKEN
        
        if not all([JIRA_URL, JIRA_USERNAME, JIRA_API_TOKEN]):
            print(f"Error: Missing required environment variables JIRA_URL={JIRA_URL}, JIRA_USERNAME={JIRA_USERNAME}, JIRA_API_TOKEN={JIRA_API_TOKEN}")
            return
        else:
            print(f"Environment variables loaded successfully JIRA_URL={JIRA_URL}, JIRA_USERNAME={JIRA_USERNAME}, JIRA_API_TOKEN={JIRA_API_TOKEN}")
        
        jira_client = JiraClient(JIRA_URL, JIRA_USERNAME, JIRA_API_TOKEN)
        print(f"Jira client initialized: {jira_client.client}")


        incident = {k.lower(): v for k, v in incident.items()} 
        
        summary = f"E:{incident['error_id']} | {incident['error_message']}"
        description = build_description(incident, rca)
        ticket_key = jira_client.create_ticket(
            project_key="SCRUM",
            issue_type="Story",
            summary=summary,
            description=description,
            priority='High'
        )
        
        if ticket_key:
            print(f"Ticket Created: {ticket_key}")
            jira_client.add_comment(ticket_key, "This ticket was automatically created by monitoring pipeline.")
            
            send_teams_notification(ticket_key, summary)
        else:
            print("Ticket creation failed.")
            
        
        dba_jira_details = insert_jira_ticket_details(ticket_key, incident, rca, db_manager)

        if dba_jira_details:
            return True
        else:
            return False 
        
    except Exception as e:
        print(f"Error inserting JIRA ticket details to DB: {e}")
        return False
    except Exception as e:
        print(f"Error creating JIRA ticket: {e}")
        return False 
